spring:

  application:
    name: OrderClient

  datasource:
    url: jdbc:h2:mem:orderDB
    driverClassName: org.h2.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
application-description: 'ORDER_CLIENT'
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4318
#      protocol: http/protobuf
#  resource:
#    attributes:
#      service.name: orders-service
#  instrumentation:
#    http:
#      enabled: true
#    spring-web:
#      enabled: true
#    jdbc:
#      enabled: true
#
#exporters:
#  prometheus:
#    endpoint: "0.0.0.0:9464"

server:
  port: 9090