spring:

  application:
    name: InventoryClient


  datasource:
    url: jdbc:h2:mem:orderDB
    driverClassName: org.h2.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
application-description: 'INVENTORY_CLIENT'

server:
  port: 9091